project_id = "vqixktvgtmqtviaauwlr"

[functions.exchange-rates]
verify_jwt = false

[functions.order-status-email]
verify_jwt = true

[functions.longevity-chat]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.webhook-receiver]
verify_jwt = false

[functions.order-tracking]
verify_jwt = false